// 1. Users
const users = [
  { id: 1, name: "John Doe", email: "john.doe@example.com", role: "Admin", status: "Active" },
  { id: 2, name: "Jane Smith", email: "jane.smith@example.com", role: "User", status: "Inactive" },
  { id: 3, name: "Mike Johnson", email: "mike.johnson@example.com", role: "Editor", status: "Active" },
  { id: 4, name: "Emily Brown", email: "emily.brown@example.com", role: "User", status: "Pending" },
  { id: 5, name: "David Lee", email: "david.lee@example.com", role: "Manager", status: "Active" },
  { id: 6, name: "Sarah Wilson", email: "sarah.wilson@example.com", role: "User", status: "Active" },
  { id: 7, name: "Robert Taylor", email: "robert.taylor@example.com", role: "Admin", status: "Inactive" },
  { id: 8, name: "Maria Garcia", email: "maria.garcia@example.com", role: "Editor", status: "Active" },
  { id: 9, name: "James Martinez", email: "james.martinez@example.com", role: "User", status: "Pending" },
  { id: 10, name: "Patricia Rodriguez", email: "patricia.rodriguez@example.com", role: "Manager", status: "Active" },
  { id: 11, name: "Michael Davis", email: "michael.davis@example.com", role: "User", status: "Active" },
  { id: 12, name: "Linda Miller", email: "linda.miller@example.com", role: "Editor", status: "Inactive" },
  { id: 13, name: "William Garcia", email: "william.garcia@example.com", role: "Admin", status: "Active" },
  { id: 14, name: "Elizabeth Wilson", email: "elizabeth.wilson@example.com", role: "User", status: "Active" },
  { id: 15, name: "Richard Moore", email: "richard.moore@example.com", role: "Manager", status: "Pending" },
  { id: 16, name: "Jennifer Taylor", email: "jennifer.taylor@example.com", role: "User", status: "Active" },
  { id: 17, name: "Charles Anderson", email: "charles.anderson@example.com", role: "Editor", status: "Active" },
  { id: 18, name: "Susan Thomas", email: "susan.thomas@example.com", role: "User", status: "Inactive" },
  { id: 19, name: "Joseph Jackson", email: "joseph.jackson@example.com", role: "Admin", status: "Active" },
  { id: 20, name: "Margaret White", email: "margaret.white@example.com", role: "Manager", status: "Active" },
  { id: 21, name: "Thomas Harris", email: "thomas.harris@example.com", role: "User", status: "Pending" },
  { id: 22, name: "Dorothy Martin", email: "dorothy.martin@example.com", role: "Editor", status: "Active" },
  { id: 23, name: "Christopher Thompson", email: "christopher.thompson@example.com", role: "User", status: "Active" },
  { id: 24, name: "Karen Martinez", email: "karen.martinez@example.com", role: "Admin", status: "Inactive" },
  { id: 25, name: "Daniel Robinson", email: "daniel.robinson@example.com", role: "Manager", status: "Active" }
];

// 2. Products
const products = [
  { id: 101, name: "MacBook Pro M3", category: "Electronics", price: 129999, stock: 8 },
  { id: 102, name: "Sony WH-1000XM5", category: "Electronics", price: 29999, stock: 45 },
  { id: 103, name: "Ergonomic Office Chair", category: "Furniture", price: 15999, stock: 12 },
  { id: 104, name: "Mechanical Keyboard", category: "Accessories", price: 4999, stock: 30 },
  { id: 105, name: "Wireless Mouse", category: "Accessories", price: 2499, stock: 55 },
  { id: 106, name: "iPhone 15 Pro Max", category: "Electronics", price: 149999, stock: 5 },
  { id: 107, name: "Dell XPS 15", category: "Electronics", price: 89999, stock: 10 },
  { id: 108, name: "Standing Desk", category: "Furniture", price: 24999, stock: 7 },
  { id: 109, name: "USB-C Hub", category: "Accessories", price: 3499, stock: 40 },
  { id: 110, name: "Samsung Galaxy S24", category: "Electronics", price: 79999, stock: 15 },
  { id: 111, name: "Office Desk Lamp", category: "Furniture", price: 2999, stock: 25 },
  { id: 112, name: "Bluetooth Speaker", category: "Electronics", price: 5999, stock: 20 },
  { id: 113, name: "Laptop Stand", category: "Accessories", price: 1999, stock: 35 },
  { id: 114, name: "Gaming Chair", category: "Furniture", price: 18999, stock: 6 },
  { id: 115, name: "iPad Pro 12.9", category: "Electronics", price: 99999, stock: 4 },
  { id: 116, name: "External SSD 1TB", category: "Accessories", price: 8999, stock: 18 },
  { id: 117, name: "Bookshelf", category: "Furniture", price: 12999, stock: 9 },
  { id: 118, name: "Smartwatch Series 9", category: "Electronics", price: 41999, stock: 12 },
  { id: 119, name: "Desk Organizer", category: "Accessories", price: 1499, stock: 50 },
  { id: 120, name: "AirPods Pro 2", category: "Electronics", price: 24999, stock: 28 },
  { id: 121, name: "Filing Cabinet", category: "Furniture", price: 7999, stock: 15 },
  { id: 122, name: "Portable Monitor", category: "Electronics", price: 15999, stock: 8 },
  { id: 123, name: "Cable Management Kit", category: "Accessories", price: 999, stock: 60 },
  { id: 124, name: "Coffee Table", category: "Furniture", price: 18999, stock: 5 },
  { id: 125, name: "Noise Cancelling Earbuds", category: "Electronics", price: 17999, stock: 22 }
];

// 3. Employees
const employees = [
  { id: 1, name: "Rahul Sharma", department: "IT", salary: 55000, city: "Delhi" },
  { id: 2, name: "Priya Singh", department: "HR", salary: 48000, city: "Lucknow" },
  { id: 3, name: "Amit Kumar", department: "Finance", salary: 60000, city: "Noida" },
  { id: 4, name: "Neha Gupta", department: "Marketing", salary: 52000, city: "Jaipur" },
  { id: 5, name: "Rohan Verma", department: "IT", salary: 58000, city: "Pune" },
  { id: 6, name: "Ananya Reddy", department: "Sales", salary: 50000, city: "Hyderabad" },
  { id: 7, name: "Vikram Patel", department: "IT", salary: 62000, city: "Ahmedabad" },
  { id: 8, name: "Meera Iyer", department: "Finance", salary: 57000, city: "Chennai" },
  { id: 9, name: "Arjun Nair", department: "HR", salary: 45000, city: "Mumbai" },
  { id: 10, name: "Deepa Joshi", department: "Marketing", salary: 51000, city: "Delhi" },
  { id: 11, name: "Suresh Menon", department: "IT", salary: 65000, city: "Bengaluru" },
  { id: 12, name: "Kavita Sharma", department: "Sales", salary: 47000, city: "Pune" },
  { id: 13, name: "Rajesh Kumar", department: "Finance", salary: 59000, city: "Mumbai" },
  { id: 14, name: "Swathi Pillai", department: "HR", salary: 46000, city: "Thiruvananthapuram" },
  { id: 15, name: "Naveen Reddy", department: "IT", salary: 63000, city: "Hyderabad" },
  { id: 16, name: "Pooja Desai", department: "Marketing", salary: 53000, city: "Ahmedabad" },
  { id: 17, name: "Manoj Gupta", department: "Finance", salary: 61000, city: "Delhi" },
  { id: 18, name: "Sneha Patel", department: "Sales", salary: 49000, city: "Surat" },
  { id: 19, name: "Kiran Rao", department: "IT", salary: 67000, city: "Bengaluru" },
  { id: 20, name: "Lalita Singh", department: "HR", salary: 44000, city: "Lucknow" },
  { id: 21, name: "Vinod Sharma", department: "Marketing", salary: 54000, city: "Jaipur" },
  { id: 22, name: "Anita Verma", department: "Finance", salary: 58000, city: "Chennai" },
  { id: 23, name: "Gautam Raj", department: "IT", salary: 64000, city: "Mumbai" },
  { id: 24, name: "Reena Menon", department: "Sales", salary: 51000, city: "Pune" },
  { id: 25, name: "Nitin Kumar", department: "HR", salary: 47000, city: "Delhi" }
];

// 4. Orders
const orders = [
  { orderId: "ORD001", customer: "John", amount: 2500, payment: "Paid", status: "Delivered" },
  { orderId: "ORD002", customer: "Jane", amount: 4200, payment: "Pending", status: "Processing" },
  { orderId: "ORD003", customer: "Mike", amount: 1800, payment: "Paid", status: "Shipped" },
  { orderId: "ORD004", customer: "Emily", amount: 7500, payment: "Paid", status: "Delivered" },
  { orderId: "ORD005", customer: "David", amount: 3200, payment: "Failed", status: "Cancelled" },
  { orderId: "ORD006", customer: "Sarah", amount: 8900, payment: "Paid", status: "Delivered" },
  { orderId: "ORD007", customer: "Robert", amount: 3400, payment: "Pending", status: "Processing" },
  { orderId: "ORD008", customer: "Maria", amount: 5600, payment: "Paid", status: "Shipped" },
  { orderId: "ORD009", customer: "James", amount: 12000, payment: "Paid", status: "Delivered" },
  { orderId: "ORD010", customer: "Patricia", amount: 2800, payment: "Failed", status: "Cancelled" },
  { orderId: "ORD011", customer: "Michael", amount: 6700, payment: "Paid", status: "Delivered" },
  { orderId: "ORD012", customer: "Linda", amount: 9500, payment: "Pending", status: "Processing" },
  { orderId: "ORD013", customer: "William", amount: 4300, payment: "Paid", status: "Shipped" },
  { orderId: "ORD014", customer: "Elizabeth", amount: 8100, payment: "Paid", status: "Delivered" },
  { orderId: "ORD015", customer: "Richard", amount: 2300, payment: "Pending", status: "Processing" },
  { orderId: "ORD016", customer: "Jennifer", amount: 5200, payment: "Paid", status: "Delivered" },
  { orderId: "ORD017", customer: "Charles", amount: 6800, payment: "Paid", status: "Shipped" },
  { orderId: "ORD018", customer: "Susan", amount: 3800, payment: "Failed", status: "Cancelled" },
  { orderId: "ORD019", customer: "Joseph", amount: 7200, payment: "Paid", status: "Delivered" },
  { orderId: "ORD020", customer: "Margaret", amount: 4600, payment: "Pending", status: "Processing" },
  { orderId: "ORD021", customer: "Thomas", amount: 5900, payment: "Paid", status: "Shipped" },
  { orderId: "ORD022", customer: "Dorothy", amount: 8400, payment: "Paid", status: "Delivered" },
  { orderId: "ORD023", customer: "Christopher", amount: 3100, payment: "Pending", status: "Processing" },
  { orderId: "ORD024", customer: "Karen", amount: 6700, payment: "Paid", status: "Delivered" },
  { orderId: "ORD025", customer: "Daniel", amount: 4800, payment: "Paid", status: "Shipped" }
];

// 5. Students
const students = [
  { id: 1, name: "Arjun Kumar", class: "BCA", marks: 89, grade: "A" },
  { id: 2, name: "Sneha Reddy", class: "BCA", marks: 76, grade: "B" },
  { id: 3, name: "Karan Singh", class: "MCA", marks: 92, grade: "A+" },
  { id: 4, name: "Pooja Sharma", class: "B.Tech", marks: 68, grade: "C" },
  { id: 5, name: "Ritika Patel", class: "MCA", marks: 81, grade: "A" },
  { id: 6, name: "Vikram Joshi", class: "B.Tech", marks: 73, grade: "B" },
  { id: 7, name: "Ananya Gupta", class: "BCA", marks: 94, grade: "A+" },
  { id: 8, name: "Rahul Verma", class: "MCA", marks: 65, grade: "C" },
  { id: 9, name: "Meera Nair", class: "B.Tech", marks: 88, grade: "A" },
  { id: 10, name: "Suresh Menon", class: "BCA", marks: 79, grade: "B" },
  { id: 11, name: "Kavita Singh", class: "MCA", marks: 91, grade: "A+" },
  { id: 12, name: "Rajesh Kumar", class: "B.Tech", marks: 70, grade: "B" },
  { id: 13, name: "Divya Pillai", class: "BCA", marks: 86, grade: "A" },
  { id: 14, name: "Naveen Reddy", class: "MCA", marks: 77, grade: "B" },
  { id: 15, name: "Swathi Desai", class: "B.Tech", marks: 95, grade: "A+" },
  { id: 16, name: "Manoj Gupta", class: "BCA", marks: 67, grade: "C" },
  { id: 17, name: "Priya Patel", class: "MCA", marks: 83, grade: "A" },
  { id: 18, name: "Kiran Rao", class: "B.Tech", marks: 74, grade: "B" },
  { id: 19, name: "Lalita Sharma", class: "BCA", marks: 90, grade: "A+" },
  { id: 20, name: "Vinod Singh", class: "MCA", marks: 69, grade: "C" },
  { id: 21, name: "Anita Verma", class: "B.Tech", marks: 87, grade: "A" },
  { id: 22, name: "Gautam Raj", class: "BCA", marks: 78, grade: "B" },
  { id: 23, name: "Reena Menon", class: "MCA", marks: 93, grade: "A+" },
  { id: 24, name: "Nitin Kumar", class: "B.Tech", marks: 71, grade: "B" },
  { id: 25, name: "Deepa Joshi", class: "BCA", marks: 85, grade: "A" }
];

// 6. Customers
const customers = [
  { id: 1, name: "Alex Thompson", phone: "9876543210", city: "Mumbai", loyalty: "Gold" },
  { id: 2, name: "Sophia Williams", phone: "9876543211", city: "Delhi", loyalty: "Silver" },
  { id: 3, name: "Daniel Brown", phone: "9876543212", city: "Lucknow", loyalty: "Bronze" },
  { id: 4, name: "Emma Wilson", phone: "9876543213", city: "Hyderabad", loyalty: "Gold" },
  { id: 5, name: "James Davis", phone: "9876543214", city: "Pune", loyalty: "Silver" },
  { id: 6, name: "Olivia Miller", phone: "9876543215", city: "Bengaluru", loyalty: "Gold" },
  { id: 7, name: "Benjamin Taylor", phone: "9876543216", city: "Chennai", loyalty: "Bronze" },
  { id: 8, name: "Ava Martinez", phone: "9876543217", city: "Delhi", loyalty: "Silver" },
  { id: 9, name: "William Anderson", phone: "9876543218", city: "Mumbai", loyalty: "Gold" },
  { id: 10, name: "Mia Thomas", phone: "9876543219", city: "Jaipur", loyalty: "Bronze" },
  { id: 11, name: "Ethan Jackson", phone: "9876543220", city: "Noida", loyalty: "Silver" },
  { id: 12, name: "Charlotte White", phone: "9876543221", city: "Hyderabad", loyalty: "Gold" },
  { id: 13, name: "Lucas Harris", phone: "9876543222", city: "Pune", loyalty: "Bronze" },
  { id: 14, name: "Amelia Martin", phone: "9876543223", city: "Bengaluru", loyalty: "Silver" },
  { id: 15, name: "Mason Thompson", phone: "9876543224", city: "Delhi", loyalty: "Gold" },
  { id: 16, name: "Harper Garcia", phone: "9876543225", city: "Mumbai", loyalty: "Bronze" },
  { id: 17, name: "Logan Robinson", phone: "9876543226", city: "Chennai", loyalty: "Silver" },
  { id: 18, name: "Evelyn Clark", phone: "9876543227", city: "Lucknow", loyalty: "Gold" },
  { id: 19, name: "Jackson Rodriguez", phone: "9876543228", city: "Hyderabad", loyalty: "Bronze" },
  { id: 20, name: "Ella Lewis", phone: "9876543229", city: "Pune", loyalty: "Silver" },
  { id: 21, name: "Aiden Lee", phone: "9876543230", city: "Delhi", loyalty: "Gold" },
  { id: 22, name: "Scarlett Walker", phone: "9876543231", city: "Mumbai", loyalty: "Bronze" },
  { id: 23, name: "Carter Hall", phone: "9876543232", city: "Bengaluru", loyalty: "Silver" },
  { id: 24, name: "Grace Allen", phone: "9876543233", city: "Chennai", loyalty: "Gold" },
  { id: 25, name: "Owen Young", phone: "9876543234", city: "Noida", loyalty: "Bronze" }
];

// 7. Invoices
const invoices = [
  { invoiceNo: "INV001", client: "ABC Ltd", total: 15000, dueDate: "2026-08-01", status: "Paid" },
  { invoiceNo: "INV002", client: "XYZ Pvt Ltd", total: 28000, dueDate: "2026-08-10", status: "Pending" },
  { invoiceNo: "INV003", client: "TechSoft Solutions", total: 12000, dueDate: "2026-07-30", status: "Paid" },
  { invoiceNo: "INV004", client: "Digital Hub India", total: 45000, dueDate: "2026-08-15", status: "Overdue" },
  { invoiceNo: "INV005", client: "Cloud Inc Technologies", total: 17000, dueDate: "2026-08-05", status: "Pending" },
  { invoiceNo: "INV006", client: "Global Corp", total: 32000, dueDate: "2026-07-25", status: "Paid" },
  { invoiceNo: "INV007", client: "Innovate Solutions", total: 21000, dueDate: "2026-08-20", status: "Pending" },
  { invoiceNo: "INV008", client: "Bright Future Ltd", total: 38000, dueDate: "2026-07-15", status: "Paid" },
  { invoiceNo: "INV009", client: "Cyber Tech Systems", total: 42000, dueDate: "2026-08-25", status: "Overdue" },
  { invoiceNo: "INV010", client: "Smart Solutions Inc", total: 19000, dueDate: "2026-07-28", status: "Pending" },
  { invoiceNo: "INV011", client: "Eco Friendly Corp", total: 25000, dueDate: "2026-08-12", status: "Paid" },
  { invoiceNo: "INV012", client: "Pacific Industries", total: 35000, dueDate: "2026-07-20", status: "Overdue" },
  { invoiceNo: "INV013", client: "Atlantic Software", total: 16000, dueDate: "2026-08-18", status: "Pending" },
  { invoiceNo: "INV014", client: "NextGen Systems", total: 48000, dueDate: "2026-08-08", status: "Paid" },
  { invoiceNo: "INV015", client: "Prime Services Ltd", total: 23000, dueDate: "2026-07-22", status: "Pending" },
  { invoiceNo: "INV016", client: "Vertex Solutions", total: 31000, dueDate: "2026-08-28", status: "Paid" },
  { invoiceNo: "INV017", client: "Zenith Technologies", total: 44000, dueDate: "2026-07-18", status: "Overdue" },
  { invoiceNo: "INV018", client: "Elite Business Corp", total: 27000, dueDate: "2026-08-14", status: "Pending" },
  { invoiceNo: "INV019", client: "Sterling Industries", total: 39000, dueDate: "2026-08-02", status: "Paid" },
  { invoiceNo: "INV020", client: "Oakland Systems", total: 14000, dueDate: "2026-07-29", status: "Pending" },
  { invoiceNo: "INV021", client: "Pine Software Ltd", total: 29000, dueDate: "2026-08-22", status: "Paid" },
  { invoiceNo: "INV022", client: "Maple Technologies", total: 41000, dueDate: "2026-07-26", status: "Overdue" },
  { invoiceNo: "INV023", client: "Cedar Solutions", total: 18000, dueDate: "2026-08-09", status: "Pending" },
  { invoiceNo: "INV024", client: "Birch Innovations", total: 33000, dueDate: "2026-08-30", status: "Paid" },
  { invoiceNo: "INV025", client: "Willow Systems Inc", total: 22000, dueDate: "2026-07-19", status: "Pending" }
];

// 8. Tasks
const tasks = [
  { id: 1, title: "Design Homepage Layout", priority: "High", assignee: "John", status: "Completed" },
  { id: 2, title: "Fix Login Authentication Bug", priority: "Medium", assignee: "Jane", status: "In Progress" },
  { id: 3, title: "Write API Documentation", priority: "Low", assignee: "Mike", status: "Pending" },
  { id: 4, title: "Deploy Backend Services", priority: "High", assignee: "Emily", status: "Completed" },
  { id: 5, title: "Test Mobile Application", priority: "Medium", assignee: "David", status: "In Progress" },
  { id: 6, title: "Create Database Schema", priority: "High", assignee: "Sarah", status: "Completed" },
  { id: 7, title: "Implement Search Feature", priority: "Medium", assignee: "Robert", status: "Pending" },
  { id: 8, title: "Optimize Website Performance", priority: "High", assignee: "Maria", status: "In Progress" },
  { id: 9, title: "Setup CI/CD Pipeline", priority: "Medium", assignee: "James", status: "Completed" },
  { id: 10, title: "Design Email Templates", priority: "Low", assignee: "Patricia", status: "Pending" },
  { id: 11, title: "Implement Payment Gateway", priority: "High", assignee: "Michael", status: "In Progress" },
  { id: 12, title: "Create User Dashboard", priority: "Medium", assignee: "Linda", status: "Completed" },
  { id: 13, title: "Fix CSS Responsive Issues", priority: "Low", assignee: "William", status: "Pending" },
  { id: 14, title: "Implement OAuth2.0 Login", priority: "High", assignee: "Elizabeth", status: "Completed" },
  { id: 15, title: "Write Unit Tests", priority: "Medium", assignee: "Richard", status: "In Progress" },
  { id: 16, title: "Design Logo and Branding", priority: "High", assignee: "Jennifer", status: "Completed" },
  { id: 17, title: "Setup Server Monitoring", priority: "Medium", assignee: "Charles", status: "Pending" },
  { id: 18, title: "Implement File Upload", priority: "High", assignee: "Susan", status: "In Progress" },
  { id: 19, title: "Create Product API Endpoints", priority: "Medium", assignee: "Joseph", status: "Completed" },
  { id: 20, title: "Design Mobile Navigation", priority: "Low", assignee: "Margaret", status: "Pending" },
  { id: 21, title: "Implement Chat Feature", priority: "High", assignee: "Thomas", status: "In Progress" },
  { id: 22, title: "Setup Multi-language Support", priority: "Medium", assignee: "Dorothy", status: "Completed" },
  { id: 23, title: "Fix Security Vulnerabilities", priority: "High", assignee: "Christopher", status: "Pending" },
  { id: 24, title: "Create Admin Panel", priority: "Medium", assignee: "Karen", status: "In Progress" },
  { id: 25, title: "Implement Analytics Tracking", priority: "Low", assignee: "Daniel", status: "Completed" }
];

// 9. Payments
const payments = [
  { id: 1, payer: "John Doe", method: "UPI", amount: 1200, status: "Success" },
  { id: 2, payer: "Jane Smith", method: "Card", amount: 5400, status: "Success" },
  { id: 3, payer: "Mike Johnson", method: "Net Banking", amount: 3000, status: "Pending" },
  { id: 4, payer: "Emily Brown", method: "Cash", amount: 900, status: "Success" },
  { id: 5, payer: "David Lee", method: "Wallet", amount: 2200, status: "Failed" },
  { id: 6, payer: "Sarah Wilson", method: "UPI", amount: 3500, status: "Success" },
  { id: 7, payer: "Robert Taylor", method: "Card", amount: 6800, status: "Pending" },
  { id: 8, payer: "Maria Garcia", method: "Net Banking", amount: 4500, status: "Success" },
  { id: 9, payer: "James Martinez", method: "Cash", amount: 1500, status: "Success" },
  { id: 10, payer: "Patricia Rodriguez", method: "Wallet", amount: 2800, status: "Failed" },
  { id: 11, payer: "Michael Davis", method: "UPI", amount: 4200, status: "Success" },
  { id: 12, payer: "Linda Miller", method: "Card", amount: 3100, status: "Pending" },
  { id: 13, payer: "William Garcia", method: "Net Banking", amount: 5600, status: "Success" },
  { id: 14, payer: "Elizabeth Wilson", method: "Cash", amount: 1800, status: "Success" },
  { id: 15, payer: "Richard Moore", method: "Wallet", amount: 2900, status: "Pending" },
  { id: 16, payer: "Jennifer Taylor", method: "UPI", amount: 4700, status: "Success" },
  { id: 17, payer: "Charles Anderson", method: "Card", amount: 6200, status: "Success" },
  { id: 18, payer: "Susan Thomas", method: "Net Banking", amount: 3300, status: "Failed" },
  { id: 19, payer: "Joseph Jackson", method: "Cash", amount: 1100, status: "Success" },
  { id: 20, payer: "Margaret White", method: "Wallet", amount: 5100, status: "Pending" },
  { id: 21, payer: "Thomas Harris", method: "UPI", amount: 3900, status: "Success" },
  { id: 22, payer: "Dorothy Martin", method: "Card", amount: 2700, status: "Success" },
  { id: 23, payer: "Christopher Thompson", method: "Net Banking", amount: 4800, status: "Pending" },
  { id: 24, payer: "Karen Martinez", method: "Cash", amount: 1600, status: "Success" },
  { id: 25, payer: "Daniel Robinson", method: "Wallet", amount: 5300, status: "Success" }
];

// 10. Attendance
const attendance = [
  { id: 1, employee: "Rahul Sharma", date: "2026-07-01", checkIn: "09:05", status: "Present" },
  { id: 2, employee: "Priya Singh", date: "2026-07-01", checkIn: "09:30", status: "Late" },
  { id: 3, employee: "Amit Kumar", date: "2026-07-01", checkIn: "-", status: "Absent" },
  { id: 4, employee: "Neha Gupta", date: "2026-07-01", checkIn: "08:55", status: "Present" },
  { id: 5, employee: "Rohan Verma", date: "2026-07-01", checkIn: "09:10", status: "Present" },
  { id: 6, employee: "Ananya Reddy", date: "2026-07-02", checkIn: "09:00", status: "Present" },
  { id: 7, employee: "Vikram Patel", date: "2026-07-02", checkIn: "09:45", status: "Late" },
  { id: 8, employee: "Meera Iyer", date: "2026-07-02", checkIn: "-", status: "Absent" },
  { id: 9, employee: "Arjun Nair", date: "2026-07-02", checkIn: "08:50", status: "Present" },
  { id: 10, employee: "Deepa Joshi", date: "2026-07-02", checkIn: "09:15", status: "Present" },
  { id: 11, employee: "Suresh Menon", date: "2026-07-03", checkIn: "09:00", status: "Present" },
  { id: 12, employee: "Kavita Sharma", date: "2026-07-03", checkIn: "09:35", status: "Late" },
  { id: 13, employee: "Rajesh Kumar", date: "2026-07-03", checkIn: "08:45", status: "Present" },
  { id: 14, employee: "Swathi Pillai", date: "2026-07-03", checkIn: "-", status: "Absent" },
  { id: 15, employee: "Naveen Reddy", date: "2026-07-03", checkIn: "09:05", status: "Present" },
  { id: 16, employee: "Pooja Desai", date: "2026-07-04", checkIn: "09:00", status: "Present" },
  { id: 17, employee: "Manoj Gupta", date: "2026-07-04", checkIn: "09:40", status: "Late" },
  { id: 18, employee: "Sneha Patel", date: "2026-07-04", checkIn: "08:55", status: "Present" },
  { id: 19, employee: "Kiran Rao", date: "2026-07-04", checkIn: "-", status: "Absent" },
  { id: 20, employee: "Lalita Singh", date: "2026-07-04", checkIn: "09:10", status: "Present" },
  { id: 21, employee: "Vinod Sharma", date: "2026-07-05", checkIn: "09:00", status: "Present" },
  { id: 22, employee: "Anita Verma", date: "2026-07-05", checkIn: "09:25", status: "Late" },
  { id: 23, employee: "Gautam Raj", date: "2026-07-05", checkIn: "08:50", status: "Present" },
  { id: 24, employee: "Reena Menon", date: "2026-07-05", checkIn: "-", status: "Absent" },
  { id: 25, employee: "Nitin Kumar", date: "2026-07-05", checkIn: "09:15", status: "Present" }
];

export {
  users,
  products,
  employees,
  orders,
  students,
  customers,
  invoices,
  tasks,
  payments,
  attendance
};